version: "{build}-{branch}"
os: Windows Server 2012 R2
build: off
deploy: off
shallow_clone: true
clone_depth: 1

install:
  - ps: Install-Product node 6
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm test
  - sh integration_test
